name: Build Android APK

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Generate Wrapper if missing
      run: gradle wrapper

    # این مرحله مطمئن می‌شود فایل gradle.properties با مقادیر لازم حتماً وجود دارد
    - name: Inject gradle properties
      run: |
        echo "android.useAndroidX=true" >> gradle.properties
        echo "android.enableJetpackCompilationAndIntegrationCheck=true" >> gradle.properties

    - name: Make Gradlew Executable
      run: chmod +x gradlew

    - name: Build APK
      run: ./gradlew assembleDebug --no-daemon

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: RBNIS-Rhythm-Player-APK
        path: app/build/outputs/apk/debug/*.apk
